# Base configs
baseurl: "https://house.carromeu.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Solar da Carlota"
subtitle: "Em breve, seu novo lar!"
author: "Camilo Carromeu"
header:
 title: "Casa-condomínio à venda"
 subtitle: "na Vila Carlota"
footer:
 name: "Seu novo lar te espera..."
 about: "Com 225m² de terreno privativo e 150m² de área construída, esta casa térrea na Vila Carlota exala aconchego e elegância. Possuindo cômodos espaçosos e localizada em um seguro condomínio fechado de 37 casas próximo à UFMS e a poucos metros do Comper da Spipe Calarge, é ideal para casais com filhos pequenos e pets."
 contact: "Quer saber mais? Contacte-nos pelo <a href=\"https://api.whatsapp.com/send?phone=5567981118060\" target=\"_blank\">WhatsApp</a> ou pelo anúncio na <a href=\"https://olx.com.br/\" target=\"_blank\">OLX</a>."
